### Preprocessing rawdata

In [80]:
import pandas as pd
import numpy as np

In [81]:
#Load data into Mdf and Pdf
Mdf = pd.read_csv('student-mat.csv',sep=';')
Pdf = pd.read_csv('student-por.csv',sep=';')

In [82]:
#Add a Subject column for Mdf and Pdf
Mdf['Subject'] = 'M'
Pdf['Subject'] = 'P'

In [83]:
#Identify student who took both Math and Portuguese classes
df = pd.merge(Mdf,Pdf,on=["school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet"], suffixes=('_M','_P'))

In [104]:
#In Mdf, replace the values in G3 as an average score of Math and Portuguese. 
df.loc[:,'new_G3'] = (df.G3_M + df.G3_P)/2
#Merge df back with Mdf, so we have a dataset (Mdf4) for students who take math only and who take both classes with G3 representing the average score.
Mdf2 = df.drop(['guardian_P', 'traveltime_P',
       'studytime_P', 'failures_P', 'schoolsup_P', 'famsup_P', 'paid_P',
       'activities_P', 'higher_P', 'romantic_P', 'famrel_P', 'freetime_P',
       'goout_P', 'Dalc_P', 'Walc_P', 'health_P', 'absences_P', 'G1_P', 'G2_P',
       'G3_P', 'Subject_P'], axis=1)
Mdf2.columns = ['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences',
       'G1', 'G2', 'G3', 'Subject', 'new_G3']
Mdf3 = pd.concat([Mdf, Mdf2])
Mdf3[['G3','new_G3']]
Mdf4 = Mdf3.drop_duplicates(['Dalc', 'Fedu', 'Fjob', 'G1', 'G2', 'G3', 'Medu', 'Mjob', 'Pstatus',
       'Subject', 'Walc', 'absences', 'activities', 'address', 'age',
       'failures', 'famrel', 'famsize', 'famsup', 'freetime', 'goout',
       'guardian', 'health', 'higher', 'internet', 'nursery', 'paid',
       'reason', 'romantic', 'school', 'schoolsup', 'sex', 'studytime',
       'traveltime'], keep='last')
Mdf4.Subject = np.where(Mdf4.new_G3.isnull(), Mdf4.Subject, 'B')
Mdf4.new_G3 = np.where(Mdf4.new_G3.isnull(), Mdf4.G3, Mdf4.new_G3)
Mdf4 = Mdf4.drop('G3', axis=1)
Mdf4 = Mdf4.rename(columns = {'new_G3':'G3'})
Mdf4.G3 = Mdf4.G3.astype(int)
Mdf4.dtypes

/Users/Jing/anaconda/lib/python3.6/site-packages/pandas/core/generic.py:2773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


Dalc           int64
Fedu           int64
Fjob          object
G1             int64
G2             int64
Medu           int64
Mjob          object
Pstatus       object
Subject       object
Walc           int64
absences       int64
activities    object
address       object
age            int64
failures       int64
famrel         int64
famsize       object
famsup        object
freetime       int64
goout          int64
guardian      object
health         int64
higher        object
internet      object
G3             int64
nursery       object
paid          object
reason        object
romantic      object
school        object
schoolsup     object
sex           object
studytime      int64
traveltime     int64
dtype: object

In [105]:
#Identify students who took Portuguese class only (Pdf4).
Pdf2 = df.drop(['guardian_M', 'traveltime_M', 'studytime_M',
       'failures_M', 'schoolsup_M', 'famsup_M', 'paid_M', 'activities_M',
       'higher_M', 'romantic_M', 'famrel_M',
       'freetime_M', 'goout_M', 'Dalc_M', 'Walc_M', 'health_M', 'absences_M',
       'G1_M', 'G2_M', 'G3_M', 'Subject_M'], axis=1)
Pdf2.columns = (['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'nursery', 'internet', 'guardian',
       'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup',
       'paid', 'activities', 'higher', 'romantic', 'famrel',
       'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences',
       'G1', 'G2', 'G3', 'Subject', 'new_G3'])
Pdf3 = pd.concat([Pdf, Pdf2])
Pdf4 = Pdf3.drop_duplicates(["school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet"], keep=False)
Pdf4 = Pdf4.drop('new_G3', axis=1)
Pdf4.dtypes

Dalc           int64
Fedu           int64
Fjob          object
G1             int64
G2             int64
G3             int64
Medu           int64
Mjob          object
Pstatus       object
Subject       object
Walc           int64
absences       int64
activities    object
address       object
age            int64
failures       int64
famrel         int64
famsize       object
famsup        object
freetime       int64
goout          int64
guardian      object
health         int64
higher        object
internet      object
nursery       object
paid          object
reason        object
romantic      object
school        object
schoolsup     object
sex           object
studytime      int64
traveltime     int64
dtype: object

In [108]:
#Concatenate Mdf4 and Pdft. The new dataset INPUTdf representing students from Math, Portuguese, or both classes with an averag score G3
INPUTdf = pd.concat([Mdf4,Pdf4])
INPUTdf = INPUTdf.drop(['G1', 'G2', 'paid'], axis=1) #paid - extra paid classes within the course subject (Math or Portuguese) (binary: yes or no)
INPUTdf.dtypes

Dalc           int64
Fedu           int64
Fjob          object
G3             int64
Medu           int64
Mjob          object
Pstatus       object
Subject       object
Walc           int64
absences       int64
activities    object
address       object
age            int64
failures       int64
famrel         int64
famsize       object
famsup        object
freetime       int64
goout          int64
guardian      object
health         int64
higher        object
internet      object
nursery       object
reason        object
romantic      object
school        object
schoolsup     object
sex           object
studytime      int64
traveltime     int64
dtype: object

In [110]:
# #split rawData into trainData and testData
from sklearn.model_selection import train_test_split
y = INPUTdf['G3']
X = INPUTdf[['Dalc', 'Fedu', 'Fjob', 'Medu', 'Mjob', 'Pstatus', 'Subject',
       'Walc', 'absences', 'activities', 'address', 'age', 'failures',
       'famrel', 'famsize', 'famsup', 'freetime', 'goout', 'guardian',
       'health', 'higher', 'internet', 'nursery', 'reason',
       'romantic', 'school', 'schoolsup', 'sex', 'studytime', 'traveltime']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state=42)

In [112]:
#Dummy code categorical variables.
X_train = pd.get_dummies(X_train)
X_train.head()

Dalc  Fedu  Medu  Walc  absences  age  failures  famrel  freetime  goout  \
266     1     2     2     1         0   18         0       4         3      3   
35      1     3     2     1         0   15         0       3         5      1   
111     1     3     3     1         2   16         0       5         3      3   
5       1     3     4     2        10   16         0       5         4      2   
44      2     2     2     2        14   16         1       4         3      3   

     ...    reason_other  reason_reputation  romantic_no  romantic_yes  \
266  ...               0                  0            0             1   
35   ...               1                  0            1             0   
111  ...               0                  0            1             0   
5    ...               0                  1            1             0   
44   ...               0                  0            1             0   

     school_GP  school_MS  schoolsup_no  schoolsup_yes  sex_F  sex_M  
266          1          0             1              0      1      0  
35           1          0             1              0      1      0  
111          1          0             1              0      0      1  
5            1          0             1              0      0      1  
44           1          0             0              1      1      0  

[5 rows x 57 columns]

In [113]:
#center and scale varialbes
from sklearn import preprocessing
X = np.array(X_train)
X

array([[1, 2, 2, ..., 0, 1, 0],
       [1, 3, 2, ..., 0, 1, 0],
       [1, 3, 3, ..., 0, 0, 1],
       ..., 
       [2, 2, 3, ..., 0, 0, 1],
       [1, 2, 2, ..., 1, 1, 0],
       [1, 2, 2, ..., 0, 1, 0]])

In [114]:
X_scaled = preprocessing.scale(X)

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


In [115]:
X_scaled.mean(axis=0)

array([  8.94139349e-17,   1.60945083e-16,  -9.68650961e-18,
         8.79237026e-17,   1.19218580e-17,  -9.35865852e-16,
         2.08632515e-17,  -1.01335793e-16,   5.96092899e-17,
         1.02826025e-16,   2.98046450e-17,   4.17265029e-17,
         1.25179509e-16,  -4.17265029e-17,  -5.06678964e-17,
        -2.38437160e-17,   2.68241805e-17,   2.98046450e-17,
         3.57655739e-17,  -1.19218580e-17,   8.94139349e-17,
        -2.08632515e-17,   7.45116124e-17,  -1.63925547e-17,
        -9.68650961e-17,  -3.27851095e-17,   3.57655739e-17,
         1.01335793e-16,  -2.08632515e-17,   2.08632515e-17,
        -3.57655739e-17,   3.57655739e-17,  -1.01335793e-16,
         3.57655739e-17,   8.34530059e-17,  -8.34530059e-17,
         8.79237026e-17,   5.51385932e-17,   0.00000000e+00,
        -1.19218580e-17,   1.37101367e-16,  -7.22762640e-17,
         9.94730025e-17,  -8.34530059e-17,   8.34530059e-17,
        -1.78827870e-17,  -1.49023225e-17,  -2.68241805e-17,
         8.94139349e-18,

In [116]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.])

In [117]:
#center variables
X_centered = preprocessing.scale(X, with_mean=True, with_std=False)

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


In [118]:
X_centered.mean(axis=0)

array([  3.87460384e-17,   8.34530059e-17,   8.94139349e-18,
         1.07296722e-16,   2.38437160e-17,  -1.21602951e-15,
         3.57655739e-17,  -1.01335793e-16,   4.76874319e-17,
         1.43062296e-16,  -5.96092899e-18,   2.98046450e-17,
         8.64334704e-17,   1.26669741e-17,   3.72558062e-18,
         2.98046450e-17,  -9.31395155e-18,   1.93730192e-17,
         3.42753417e-17,  -1.49023225e-18,   2.23534837e-17,
        -2.98046450e-18,   2.98046450e-18,   2.27260418e-17,
        -4.76874319e-17,  -5.96092899e-18,  -5.96092899e-18,
         3.57655739e-17,  -5.96092899e-18,   5.96092899e-18,
        -2.23534837e-17,   2.23534837e-17,  -3.27851095e-17,
         5.96092899e-18,   2.38437160e-17,  -2.38437160e-17,
         1.19218580e-17,   2.01181353e-17,   1.04316257e-17,
        -1.75102289e-17,   4.17265029e-17,  -1.75102289e-17,
         4.76874319e-17,  -1.63925547e-17,   3.27851095e-17,
        -2.08632515e-17,   1.93730192e-17,   2.83144127e-17,
        -4.47069674e-18,