### Preprocessing student-mat.csv

In [4]:
import pandas as pd

In [5]:
#load data into rawdata
dfm = pd.read_csv('student-mat.csv',sep=';')

In [6]:
dfm.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [7]:
dfm.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [8]:
dfm.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [9]:
dfm.select_dtypes(include=['object'])

school sex address famsize Pstatus      Mjob      Fjob      reason  \
0       GP   F       U     GT3       A   at_home   teacher      course   
1       GP   F       U     GT3       T   at_home     other      course   
2       GP   F       U     LE3       T   at_home     other       other   
3       GP   F       U     GT3       T    health  services        home   
4       GP   F       U     GT3       T     other     other        home   
5       GP   M       U     LE3       T  services     other  reputation   
6       GP   M       U     LE3       T     other     other        home   
7       GP   F       U     GT3       A     other   teacher        home   
8       GP   M       U     LE3       A  services     other        home   
9       GP   M       U     GT3       T     other     other        home   
10      GP   F       U     GT3       T   teacher    health  reputation   
11      GP   F       U     GT3       T  services     other  reputation   
12      GP   M       U     LE3       T    health  services      course   
13      GP   M       U     GT3       T   teacher     other      course   
14      GP   M       U     GT3       A     other     other        home   
15      GP   F       U     GT3       T    health     other        home   
16      GP   F       U     GT3       T  services  services  reputation   
17      GP   F       U     GT3       T     other     other  reputation   
18      GP   M       U     GT3       T  services  services      course   
19      GP   M       U     LE3       T    health     other        home   
20      GP   M       U     GT3       T   teacher     other  reputation   
21      GP   M       U     GT3       T    health    health       other   
22      GP   M       U     LE3       T   teacher     other      course   
23      GP   M       U     LE3       T     other     other  reputation   
24      GP   F       R     GT3       T  services    health      course   
25      GP   F       U     GT3       T  services  services        home   
26      GP   M       U     GT3       T     other     other        home   
27      GP   M       U     GT3       T    health  services       other   
28      GP   M       U     LE3       A  services     other        home   
29      GP   M       U     GT3       T   teacher   teacher        home   
..     ...  ..     ...     ...     ...       ...       ...         ...   
365     MS   M       R     GT3       T   at_home     other      course   
366     MS   M       U     LE3       T   teacher  services       other   
367     MS   F       R     GT3       T     other  services  reputation   
368     MS   F       U     GT3       T   at_home  services      course   
369     MS   F       R     GT3       T     other   teacher       other   
370     MS   F       U     LE3       T  services  services        home   
371     MS   M       R     LE3       T   at_home  services       other   
372     MS   F       U     GT3       T     other   at_home        home   
373     MS   F       R     GT3       T     other     other      course   
374     MS   F       R     LE3       T     other     other  reputation   
375     MS   F       R     GT3       T     other     other        home   
376     MS   F       U     GT3       T    health     other      course   
377     MS   F       R     LE3       T   teacher  services      course   
378     MS   F       U     GT3       T     other     other        home   
379     MS   F       R     GT3       T   at_home     other  reputation   
380     MS   M       U     GT3       T   teacher   teacher        home   
381     MS   M       R     GT3       T     other     other       other   
382     MS   M       U     GT3       T     other  services        home   
383     MS   M       R     GT3       T     other  services       other   
384     MS   M       R     GT3       T     other     other        home   
385     MS   F       R     GT3       T   at_home     other       other   
386     MS   F       R     GT3       T   teacher   at_home  reputation   
387     

In [10]:
#Dummy code categorical variables.
dfm = pd.get_dummies(dfm)
dfm.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         3       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Dalc      ...       activities_no  activities_yes  nursery_no  nursery_yes  \
0     1      ...                   1               0           0            1   
1     1      ...                   1               0           1            0   
2     2      ...                   1               0           0            1   
3     1      ...                   0               1           0            1   
4     1      ...                   1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 59 columns]

In [11]:
dfm.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
Dalc                 int64
Walc                 int64
health               int64
absences             int64
G1                   int64
G2                   int64
G3                   int64
school_GP            uint8
school_MS            uint8
sex_F                uint8
sex_M                uint8
address_R            uint8
address_U            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
r

In [12]:
#center and scale varialbes
from sklearn import preprocessing
import numpy as np

In [13]:
X = np.array(dfm)
X

array([[18,  4,  4, ...,  0,  1,  0],
       [17,  1,  1, ...,  1,  1,  0],
       [15,  1,  1, ...,  1,  1,  0],
       ..., 
       [21,  1,  1, ...,  0,  1,  0],
       [18,  3,  2, ...,  1,  1,  0],
       [19,  1,  1, ...,  1,  1,  0]])

In [14]:
X_scaled = preprocessing.scale(X)
X_scaled

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[ 1.02304645,  1.14385567,  1.36037064, ..., -2.23267743,
         0.70844982, -0.70844982],
       [ 0.23837976, -1.60000865, -1.39997047, ...,  0.44789274,
         0.70844982, -0.70844982],
       [-1.33095364, -1.60000865, -1.39997047, ...,  0.44789274,
         0.70844982, -0.70844982],
       ..., 
       [ 3.37704655, -1.60000865, -1.39997047, ..., -2.23267743,
         0.70844982, -0.70844982],
       [ 1.02304645,  0.22923423, -0.47985677, ...,  0.44789274,
         0.70844982, -0.70844982],
       [ 1.80771315, -1.60000865, -1.39997047, ...,  0.44789274,
         0.70844982, -0.70844982]])

In [15]:
X_scaled.mean(axis=0)

array([  1.22321281e-15,   5.39652711e-17,  -1.43907390e-16,
         6.29594829e-17,  -2.11363978e-16,  -1.34913178e-17,
        -1.39410284e-16,   1.07930542e-16,  -1.21421860e-16,
         1.34913178e-16,  -1.79884237e-16,   7.19536948e-17,
        -5.39652711e-17,   8.99421185e-17,  -4.94681651e-17,
        -9.44392244e-17,  -2.51837932e-16,  -3.59768474e-17,
        -8.09479066e-17,  -7.19536948e-17,   8.09479066e-17,
        -1.61895813e-16,  -6.29594829e-17,   6.29594829e-17,
         1.34913178e-17,  -1.34913178e-17,   1.03433436e-16,
        -8.99421185e-18,   2.92311885e-17,  -2.02369767e-17,
         2.58583591e-17,  -5.39652711e-17,  -3.59768474e-17,
        -1.14676201e-16,   6.29594829e-17,   7.19536948e-17,
        -1.79884237e-17,  -5.17167181e-17,   8.99421185e-18,
         7.19536948e-17,   8.99421185e-18,  -4.04739533e-17,
         0.00000000e+00,   3.59768474e-17,   5.39652711e-17,
        -8.09479066e-17,  -9.89363303e-17,   2.69826355e-17,
        -2.69826355e-17,

In [16]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [17]:
X_centered = preprocessing.scale(X,with_mean=True, with_std=False)
X_centered

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[ 1.30379747,  1.25063291,  1.47848101, ..., -0.83291139,
         0.33417722, -0.33417722],
       [ 0.30379747, -1.74936709, -1.52151899, ...,  0.16708861,
         0.33417722, -0.33417722],
       [-1.69620253, -1.74936709, -1.52151899, ...,  0.16708861,
         0.33417722, -0.33417722],
       ..., 
       [ 4.30379747, -1.74936709, -1.52151899, ..., -0.83291139,
         0.33417722, -0.33417722],
       [ 1.30379747,  0.25063291, -0.52151899, ...,  0.16708861,
         0.33417722, -0.33417722],
       [ 2.30379747, -1.74936709, -1.52151899, ...,  0.16708861,
         0.33417722, -0.33417722]])

In [18]:
X_centered.mean(axis=0)

array([  1.72688867e-15,  -3.59768474e-17,  -1.16924754e-16,
         8.09479066e-17,  -1.88878449e-16,  -4.49710592e-18,
        -1.24794689e-16,   1.18049030e-16,  -1.79884237e-16,
         9.89363303e-17,  -1.79884237e-16,   2.24855296e-16,
        -4.31722169e-16,   4.31722169e-16,  -2.51837932e-16,
        -5.21664287e-16,  -5.39652711e-17,   4.49710592e-17,
        -4.04739533e-17,  -6.29594829e-17,   2.69826355e-17,
        -6.29594829e-17,  -2.24855296e-17,   2.24855296e-17,
        -6.74565888e-18,   6.74565888e-18,   1.57398707e-17,
        -5.62138240e-18,  -4.55331975e-17,  -3.31661562e-17,
         9.27528097e-18,  -1.23670413e-17,  -1.12427648e-17,
        -5.00303034e-17,   1.91127002e-17,   2.36098061e-17,
        -2.24855296e-18,  -4.27225063e-17,  -1.91127002e-17,
         1.34913178e-17,   3.59768474e-17,  -4.04739533e-17,
         4.49710592e-18,   2.69826355e-17,  -1.79884237e-17,
        -2.69826355e-17,  -6.74565888e-17,  -1.34913178e-17,
         1.34913178e-17,

### Preprocessing student-por.csv

In [20]:
#load data into rawdata
dfp = pd.read_csv('student-por.csv',sep=';')

In [21]:
dfp.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        4   0  11  11  
1      5        3      3     1     1      3        2   9  11  11  
2      4        3      2     2     3      3        6  12  13  12  
3      3        2      2     1     1      5        0  14  14  14  
4      4        3      2     1     2      5        0  11  13  13  

[5 rows x 33 columns]

In [23]:
dfp.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [11]:
dfm.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [25]:
#Dummy code categorical variables.
dfp = pd.get_dummies(dfp)
dfp.head()

age  Medu  Fedu  traveltime  studytime  failures  famrel  freetime  goout  \
0   18     4     4           2          2         0       4         3      4   
1   17     1     1           1          2         0       5         3      3   
2   15     1     1           1          2         0       4         3      2   
3   15     4     2           1          3         0       3         2      2   
4   16     3     3           1          2         0       4         3      2   

   Dalc      ...       activities_no  activities_yes  nursery_no  nursery_yes  \
0     1      ...                   1               0           0            1   
1     1      ...                   1               0           1            0   
2     2      ...                   1               0           0            1   
3     1      ...                   0               1           0            1   
4     1      ...                   1               0           0            1   

   higher_no  higher_yes  internet_no  internet_yes  romantic_no  romantic_yes  
0          0           1            1             0            1             0  
1          0           1            0             1            1             0  
2          0           1            0             1            1             0  
3          0           1            0             1            0             1  
4          0           1            1             0            1             0  

[5 rows x 59 columns]

In [26]:
dfp.dtypes

age                  int64
Medu                 int64
Fedu                 int64
traveltime           int64
studytime            int64
failures             int64
famrel               int64
freetime             int64
goout                int64
Dalc                 int64
Walc                 int64
health               int64
absences             int64
G1                   int64
G2                   int64
G3                   int64
school_GP            uint8
school_MS            uint8
sex_F                uint8
sex_M                uint8
address_R            uint8
address_U            uint8
famsize_GT3          uint8
famsize_LE3          uint8
Pstatus_A            uint8
Pstatus_T            uint8
Mjob_at_home         uint8
Mjob_health          uint8
Mjob_other           uint8
Mjob_services        uint8
Mjob_teacher         uint8
Fjob_at_home         uint8
Fjob_health          uint8
Fjob_other           uint8
Fjob_services        uint8
Fjob_teacher         uint8
reason_course        uint8
r

In [28]:
#center and scale varialbes
Y = np.array(dfp)
Y

array([[18,  4,  4, ...,  0,  1,  0],
       [17,  1,  1, ...,  1,  1,  0],
       [15,  1,  1, ...,  1,  1,  0],
       ..., 
       [18,  1,  1, ...,  0,  1,  0],
       [17,  3,  1, ...,  1,  1,  0],
       [18,  3,  2, ...,  1,  1,  0]])

In [29]:
Y_scaled = preprocessing.scale(Y)
Y_scaled

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[ 1.03169516,  1.31021563,  1.54071544, ..., -1.81604329,
         0.76349645, -0.76349645],
       [ 0.21013668, -1.33603938, -1.18883229, ...,  0.55064767,
         0.76349645, -0.76349645],
       [-1.43298028, -1.33603938, -1.18883229, ...,  0.55064767,
         0.76349645, -0.76349645],
       ..., 
       [ 1.03169516, -1.33603938, -1.18883229, ..., -1.81604329,
         0.76349645, -0.76349645],
       [ 0.21013668,  0.42813063, -1.18883229, ...,  0.55064767,
         0.76349645, -0.76349645],
       [ 1.03169516,  0.42813063, -0.27898305, ...,  0.55064767,
         0.76349645, -0.76349645]])

In [30]:
Y_scaled.mean(axis=0)

array([ -1.75172323e-16,  -1.09482702e-16,  -3.28448106e-17,
        -7.66378914e-17,   9.57973642e-17,   3.28448106e-17,
        -1.62855519e-16,   1.86120593e-16,   7.11637563e-17,
        -3.28448106e-17,   7.93749589e-17,  -1.14956837e-16,
         2.18965404e-17,   2.84655025e-16,  -2.18965404e-17,
         1.09482702e-17,   0.00000000e+00,   0.00000000e+00,
        -5.47413510e-17,   5.47413510e-17,  -1.09482702e-16,
         1.53275783e-16,  -8.75861616e-17,  -9.03232291e-17,
         5.47413510e-17,   7.59536245e-17,  -6.56896212e-17,
         4.37930808e-17,  -1.77909391e-17,  -5.47413510e-18,
         6.02154861e-17,   6.02154861e-17,   5.47413510e-17,
         2.46336079e-17,  -4.37930808e-17,   1.09482702e-17,
        -1.09482702e-17,   6.56896212e-17,   6.56896212e-17,
         7.66378914e-17,  -5.47413510e-18,   7.66378914e-17,
        -6.56896212e-17,   2.18965404e-17,  -2.18965404e-17,
         2.73706755e-17,  -2.73706755e-17,  -5.61098848e-17,
         1.50538715e-17,

In [47]:
X_scaled.std(axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [31]:
Y_centered = preprocessing.scale(Y,with_mean=True, with_std=False)
Y_centered

/Users/Jing/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, _DataConversionWarning)


array([[ 1.25577812,  1.4853621 ,  1.69337442, ..., -0.76733436,
         0.36825886, -0.36825886],
       [ 0.25577812, -1.5146379 , -1.30662558, ...,  0.23266564,
         0.36825886, -0.36825886],
       [-1.74422188, -1.5146379 , -1.30662558, ...,  0.23266564,
         0.36825886, -0.36825886],
       ..., 
       [ 1.25577812, -1.5146379 , -1.30662558, ..., -0.76733436,
         0.36825886, -0.36825886],
       [ 0.25577812,  0.4853621 , -1.30662558, ...,  0.23266564,
         0.36825886, -0.36825886],
       [ 1.25577812,  0.4853621 , -0.30662558, ...,  0.23266564,
         0.36825886, -0.36825886]])

In [32]:
Y_centered.mean(axis=0)

array([ -1.75172323e-16,  -1.64224053e-16,  -1.53275783e-16,
        -6.56896212e-17,   1.31379242e-16,   4.65301483e-17,
        -1.57381384e-16,   1.72435256e-16,   8.75861616e-17,
        -1.25905107e-16,   2.73706755e-18,  -1.86120593e-16,
         8.75861616e-17,   8.32068535e-16,  -1.09482702e-16,
        -1.31379242e-16,   4.37930808e-17,  -4.37930808e-17,
        -3.28448106e-17,   3.28448106e-17,   0.00000000e+00,
         4.37930808e-17,  -4.51616146e-17,  -3.83189457e-17,
        -5.47413510e-18,   1.47117381e-17,  -1.09482702e-17,
         8.21120265e-18,  -6.15840199e-18,  -1.64224053e-17,
         2.46336079e-17,   1.91594728e-17,   8.21120265e-18,
         1.36853377e-17,   1.36853377e-18,   1.91594728e-17,
        -3.01077430e-17,   8.21120265e-18,   3.01077430e-17,
         5.47413510e-18,   1.09482702e-17,   2.73706755e-17,
        -8.21120265e-18,   2.18965404e-17,  -5.47413510e-18,
         5.47413510e-18,  -5.47413510e-18,  -2.80549424e-17,
         1.74488056e-17,